#baseURL = 'https://robsonvnt.me/'
languageCode = 'pt-br'
title = 'Robson Ventura'

[params]
  profileImage = "/profile-2.jpg" # Caminho para a imagem de perfil
  profileDescription = "Explorando a interseção entre tecnologia, trabalho e movimentos sociais: reflexões, experiências e ações para um futuro mais justo"


[menu]
  [[menu.main]]
    weight = 1
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categorias"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "about"
    pre = ""
    post = ""
    name = "Sobre Mim"
    url = "/about/"
    title = ""