baseURL = 'https://robsonvnt.me/'
languageCode = 'pt-br'
title = 'Robson Ventura'

[menu]
  [[menu.main]]
    weight = 1
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""